<?php

use Drupal\Core\Mail\MailManagerInterface;
use Drupal\Component\Utility\Html;

/**
 * @file
 * Contains commerce_ginger.module.
 */


use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Utility\SafeMarkup;

/**
 * Implements hook_mail
 */
function commerce_ginger_mail($key, &$message, $params) {
  if ($key != 'order_mail') {
    return;
  }
  $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
  $message['subject'] = $params['subject'];
  $renderer = \Drupal::service('renderer');
  $message['body'][] = $renderer->renderPlain($params['body']);

}

/**
 * Implements hook_form_alter().
 *
 * This implementation alters any checkout form looking for the payment pane in
 * order to attache on it css rules if only one payment method is enable.
 */
function commerce_ginger_form_commerce_checkout_form_checkout_alter(&$form, &$form_state, $form_id) {

  var_dump($form['commerce_payment']['#access']);die();
  // If the current form ID is for a checkout form...
  if (strpos($form_id, 'commerce_checkout_form_') === 0) {
    // And it specifies a valid checkout page...
    if (commerce_checkout_page_load(substr($form_id, 23))) {
      // And the current page's form includes the payment checkout pane...
      if (!empty($form['commerce_payment'])) {
        // Add css to hide the credit card input if only one payment
        // method is enable.
        var_dump($form['commerce_payment']['payment_method']['#options']);die();
        if (count($form['commerce_payment']['payment_method']['#options']) == 1) {
          $form['payment_method']['attributes']['#attached']['css'][] = array(
            'type' => 'inline',
            'data' => '#edit-commerce-payment-payment-method input {display: none;}',
          );
        }
      }
    }
  }
}


